from sqlalchemy import ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.core.enums import NoticeStatus
from app.core.ids import generate_id
from app.db.base import Base


class Notice(Base):
    """A posting on a board — a real world object created by a person or
    organization, not generated by the board being looked at (Phase 12I).
    The board itself is just a LocationFeature (Phase 4); not every
    settlement has one, and nothing marks a feature as "a board" other
    than Notices actually pointing at it."""

    __tablename__ = "notices"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: generate_id("notice"))
    campaign_id: Mapped[str] = mapped_column(ForeignKey("campaigns.id"), nullable=False)
    board_feature_id: Mapped[str] = mapped_column(ForeignKey("location_features.id"), nullable=False)
    category: Mapped[str] = mapped_column(String, nullable=False)
    title: Mapped[str] = mapped_column(String, nullable=False)
    text: Mapped[str] = mapped_column(String, nullable=False)
    author_npc_id: Mapped[str | None] = mapped_column(ForeignKey("npcs.id"), nullable=True)
    author_organization_id: Mapped[str | None] = mapped_column(
        ForeignKey("organizations.id"), nullable=True
    )
    quest_id: Mapped[str | None] = mapped_column(ForeignKey("quests.id"), nullable=True)
    status: Mapped[str] = mapped_column(String, default=NoticeStatus.ACTIVE, nullable=False)
    posted_world_minute: Mapped[int] = mapped_column(Integer, nullable=False)
    expires_world_minute: Mapped[int | None] = mapped_column(Integer, nullable=True)
