"""Phase 15H — Roads, Routes & Connections.

Every settlement/geography feature generated by Phase 15 must be actually
reachable through real LocationConnection rows — existence without
connectivity would leave content permanently unreachable under the
existing travel system. Inter-subregion connections use distances large
enough that crossing between them takes real in-game days, not minutes,
reusing app.game.travel.service's existing formula unchanged.
"""

from app.db.models.location import Location
from app.db.models.location import LocationConnection
from app.db.models.settlement import Settlement
from app.game.travel.service import calculate_travel_minutes
from app.game.world.seed import create_campaign, seed_initial_region


def _reachable_location_ids(db_session, start_id):
    seen = {start_id}
    frontier = [start_id]
    while frontier:
        current = frontier.pop()
        neighbors = (
            db_session.query(LocationConnection.to_location_id)
            .filter(LocationConnection.from_location_id == current, LocationConnection.active.is_(True))
            .all()
        )
        for (neighbor_id,) in neighbors:
            if neighbor_id not in seen:
                seen.add(neighbor_id)
                frontier.append(neighbor_id)
    return seen


def test_every_major_settlement_is_reachable_from_the_starting_village(db_session):
    campaign = create_campaign(db_session, "Campanha A")
    region, village = seed_initial_region(db_session, campaign.id)

    reachable = _reachable_location_ids(db_session, village.id)

    major_settlement_location_ids = {
        row[0]
        for row in db_session.query(Settlement.location_id)
        .join(Location, Location.id == Settlement.location_id)
        .filter(Location.region_id == region.id)
        .all()
    }

    assert major_settlement_location_ids.issubset(reachable)


def test_every_geography_feature_is_reachable_from_the_starting_village(db_session):
    campaign = create_campaign(db_session, "Campanha A")
    region, village = seed_initial_region(db_session, campaign.id)

    reachable = _reachable_location_ids(db_session, village.id)

    geography_location_ids = {
        loc.id
        for loc in db_session.query(Location)
        .filter(Location.region_id == region.id, Location.materialization_tier == 1)
        .all()
        if loc.type in (
            "plains", "forest", "hills", "mountain_range", "marsh",
            "river", "lake", "coast", "wilderness",
        )
    }

    assert geography_location_ids.issubset(reachable)


def test_inter_subregion_travel_takes_multiple_hours_at_least(db_session):
    campaign = create_campaign(db_session, "Campanha A")
    region, village = seed_initial_region(db_session, campaign.id)

    inter_subregion_connections = (
        db_session.query(LocationConnection)
        .filter(LocationConnection.connection_type == "ROAD", LocationConnection.distance >= 80)
        .all()
    )

    assert len(inter_subregion_connections) > 0
    for connection in inter_subregion_connections:
        minutes = calculate_travel_minutes(connection)
        assert minutes >= 60 * 15  # at least ~15 hours for one hop


def test_same_world_seed_reproduces_the_same_road_network(db_session):
    first_campaign = create_campaign(db_session, "Campanha 1", world_seed=555111)
    second_campaign = create_campaign(db_session, "Campanha 2", world_seed=555111)

    first_region, _ = seed_initial_region(db_session, first_campaign.id)
    second_region, _ = seed_initial_region(db_session, second_campaign.id)

    def connection_shape(region_id):
        locations_by_id = {
            loc.id: loc.name
            for loc in db_session.query(Location).filter(Location.region_id == region_id).all()
        }
        return sorted(
            (locations_by_id[c.from_location_id], locations_by_id[c.to_location_id], c.distance, c.danger)
            for c in db_session.query(LocationConnection)
            .join(Location, Location.id == LocationConnection.from_location_id)
            .filter(Location.region_id == region_id)
            .all()
        )

    assert connection_shape(first_region.id) == connection_shape(second_region.id)
