"""add knowledge fact social priority

Revision ID: 016c02c3bb5f
Revises: 98049c6720d0
Create Date: 2026-08-18 16:41:55.766157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '016c02c3bb5f'
down_revision: Union[str, None] = '98049c6720d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_facts",
        sa.Column(
            "social_priority",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_facts', 'social_priority')
    # ### end Alembic commands ###
