"""add simulated player relationships

Revision ID: 0cc9bb119cf6
Revises: 855cdc4cca86
Create Date: 2026-08-19 20:18:33.113835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0cc9bb119cf6'
down_revision: Union[str, None] = '855cdc4cca86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_simulated_player_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('simulated_player_id', sa.String(), nullable=False),
    sa.Column('familiarity', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('affinity', sa.Integer(), nullable=False),
    sa.Column('last_interaction_minute', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['simulated_player_id'], ['simulated_players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'simulated_player_id', name='uq_character_simulated_player_relationship_pair')
    )
    op.create_index('ix_character_simulated_player_relationship_campaign', 'character_simulated_player_relationships', ['campaign_id', 'character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_character_simulated_player_relationship_campaign', table_name='character_simulated_player_relationships')
    op.drop_table('character_simulated_player_relationships')
    # ### end Alembic commands ###
