"""add npc activity

Revision ID: 143e85840d91
Revises: 5d5900ba027a
Create Date: 2026-08-18 00:23:03.178779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '143e85840d91'
down_revision: Union[str, None] = '5d5900ba027a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "npcs",
        sa.Column(
            "activity",
            sa.String(),
            nullable=False,
            server_default="AVAILABLE",
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'activity')
    # ### end Alembic commands ###
