"""add simulated player activity

Revision ID: 19cbee934b87
Revises: 1f048dbc36e1
Create Date: 2026-08-19 17:34:53.909088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '19cbee934b87'
down_revision: Union[str, None] = '1f048dbc36e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulated_players', sa.Column('activity', sa.String(), server_default='AVAILABLE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulated_players', 'activity')
    # ### end Alembic commands ###
