"""add transported arrival locations

Revision ID: 1f048dbc36e1
Revises: 3239cf8ef6c2
Create Date: 2026-08-19 15:01:10.659911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f048dbc36e1'
down_revision: Union[str, None] = '3239cf8ef6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulated_player_arrival_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulated_player_arrival_locations')
    # ### end Alembic commands ###
