"""add transported arrival policy

Revision ID: 3239cf8ef6c2
Revises: 521346e37a59
Create Date: 2026-08-19 14:49:00.650404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3239cf8ef6c2'
down_revision: Union[str, None] = '521346e37a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulated_player_arrival_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('max_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('min_group_size', sa.Integer(), nullable=False),
    sa.Column('max_group_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulated_player_arrival_policies')
    # ### end Alembic commands ###
