"""add character location discovery

Revision ID: 3c4bf1ddd854
Revises: f9667339ebe0
Create Date: 2026-08-17 14:46:02.563693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c4bf1ddd854'
down_revision: Union[str, None] = 'f9667339ebe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_location_discoveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('visited_at', sa.DateTime(), nullable=True),
    sa.Column('mapped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'location_id', name='uq_character_location_discovery')
    )
    op.create_index('ix_character_location_discovery_character_status', 'character_location_discoveries', ['character_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_character_location_discovery_character_status', table_name='character_location_discoveries')
    op.drop_table('character_location_discoveries')
    # ### end Alembic commands ###
