"""add simulated player identity fields

Revision ID: 514de4ac1e9a
Revises: 9eabe3fb45ce
Create Date: 2026-08-19 12:02:32.020091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '514de4ac1e9a'
down_revision: Union[str, None] = '9eabe3fb45ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulated_players', sa.Column('personality', sa.Text(), nullable=True))
    op.add_column('simulated_players', sa.Column('background', sa.Text(), nullable=True))
    op.add_column('simulated_players', sa.Column('motivation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulated_players', 'motivation')
    op.drop_column('simulated_players', 'background')
    op.drop_column('simulated_players', 'personality')
    # ### end Alembic commands ###
