"""add scheduled simulated player arrivals

Revision ID: 521346e37a59
Revises: 83960712dbfb
Create Date: 2026-08-19 13:47:12.365404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '521346e37a59'
down_revision: Union[str, None] = '83960712dbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_simulated_player_arrivals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('scheduled_world_minute', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('executed_world_minute', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_simulated_player_arrival_due', 'scheduled_simulated_player_arrivals', ['scheduled_world_minute', 'executed_world_minute'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_simulated_player_arrival_due', table_name='scheduled_simulated_player_arrivals')
    op.drop_table('scheduled_simulated_player_arrivals')
    # ### end Alembic commands ###
