"""add character connection discovery

Revision ID: 5d5900ba027a
Revises: 3c4bf1ddd854
Create Date: 2026-08-17 15:59:41.523099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d5900ba027a'
down_revision: Union[str, None] = '3c4bf1ddd854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_connection_discoveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['location_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'connection_id', name='uq_character_connection_discovery')
    )
    op.create_index('ix_character_connection_discovery_character', 'character_connection_discoveries', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_character_connection_discovery_character', table_name='character_connection_discoveries')
    op.drop_table('character_connection_discoveries')
    # ### end Alembic commands ###
