"""add simulated player population

Revision ID: 83960712dbfb
Revises: f289cd8742d0
Create Date: 2026-08-19 13:15:31.073907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83960712dbfb'
down_revision: Union[str, None] = 'f289cd8742d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulated_player_populations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('abstract_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulated_player_populations')
    # ### end Alembic commands ###
