"""add simulated player established routines

Revision ID: 855cdc4cca86
Revises: be1a7c6e8478
Create Date: 2026-08-19 18:58:31.770575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '855cdc4cca86'
down_revision: Union[str, None] = 'be1a7c6e8478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulated_player_routines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('simulated_player_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('start_minute_of_day', sa.Integer(), nullable=False),
    sa.Column('end_minute_of_day', sa.Integer(), nullable=False),
    sa.Column('established_world_minute', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['simulated_player_id'], ['simulated_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulated_player_routines')
    # ### end Alembic commands ###
