"""add world developments

Revision ID: 98049c6720d0
Revises: 143e85840d91
Create Date: 2026-08-18 11:41:00.028358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '98049c6720d0'
down_revision: Union[str, None] = '143e85840d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_developments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('development_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('started_world_minute', sa.Integer(), nullable=True),
    sa.Column('last_updated_world_minute', sa.Integer(), nullable=True),
    sa.Column('next_update_world_minute', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_world_developments_campaign_status_next_update', 'world_developments', ['campaign_id', 'status', 'next_update_world_minute'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_world_developments_campaign_status_next_update', table_name='world_developments')
    op.drop_table('world_developments')
    # ### end Alembic commands ###
