"""add subminute world time accumulator

Revision ID: ab80f9c90d62
Revises: 0cc9bb119cf6
Create Date: 2026-08-19 21:29:06.134764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab80f9c90d62'
down_revision: Union[str, None] = '0cc9bb119cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_times', sa.Column('subminute_seconds', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_times', 'subminute_seconds')
    # ### end Alembic commands ###
