"""add simulated player temporary activity duration

Revision ID: be1a7c6e8478
Revises: 19cbee934b87
Create Date: 2026-08-19 18:25:53.091580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'be1a7c6e8478'
down_revision: Union[str, None] = '19cbee934b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulated_players', sa.Column('activity_until_world_minute', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulated_players', 'activity_until_world_minute')
    # ### end Alembic commands ###
