"""add simulated player physical description

Revision ID: f289cd8742d0
Revises: 514de4ac1e9a
Create Date: 2026-08-19 12:09:39.349266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f289cd8742d0'
down_revision: Union[str, None] = '514de4ac1e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulated_players', sa.Column('physical_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulated_players', 'physical_description')
    # ### end Alembic commands ###
