from enum import StrEnum


class CharacterStatus(StrEnum):
    ALIVE = "ALIVE"
    DEAD = "DEAD"


class CharacterXPSource(StrEnum):
    DANGER_OVERCOME = "DANGER_OVERCOME"
    SIGNIFICANT_CHALLENGE = "SIGNIFICANT_CHALLENGE"
    IMPORTANT_DISCOVERY = "IMPORTANT_DISCOVERY"
    RELEVANT_ACHIEVEMENT = "RELEVANT_ACHIEVEMENT"
    DIFFICULT_SURVIVAL = "DIFFICULT_SURVIVAL"
    IMPORTANT_OBJECTIVE = "IMPORTANT_OBJECTIVE"
    DIFFICULT_PROBLEM = "DIFFICULT_PROBLEM"
    MEANINGFUL_NEW_EXPERIENCE = "MEANINGFUL_NEW_EXPERIENCE"


class EarthProfession(StrEnum):
    CHEF = "CHEF"
    FARMER = "FARMER"
    CARPENTER = "CARPENTER"
    BLACKSMITH = "BLACKSMITH"


class ProfessionXPSource(StrEnum):
    GATHERING = "GATHERING"
    WORK = "WORK"
    CRAFTING = "CRAFTING"
    PRACTICE = "PRACTICE"


class ProfessionActivityOutcome(StrEnum):
    FAILURE = "FAILURE"
    PARTIAL = "PARTIAL"
    SUCCESS = "SUCCESS"


class ClassOfferStatus(StrEnum):
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELAYED = "DELAYED"
    ACCEPTED = "ACCEPTED"


class DomainEvidenceSource(StrEnum):
    TRAINING = "TRAINING"
    TECHNIQUE_LEARNED = "TECHNIQUE_LEARNED"
    TECHNIQUE_USED = "TECHNIQUE_USED"
    EXPERIENCE = "EXPERIENCE"
    COMBAT = "COMBAT"
    STUDY = "STUDY"
    EXPERIMENTATION = "EXPERIMENTATION"
    ACHIEVEMENT = "ACHIEVEMENT"


class CharacterAttributeKey(StrEnum):
    STRENGTH = "STRENGTH"
    AGILITY = "AGILITY"
    VITALITY = "VITALITY"
    INTELLIGENCE = "INTELLIGENCE"
    WISDOM = "WISDOM"
    ENDURANCE = "ENDURANCE"
    LUCK = "LUCK"


class AttributeEvidenceSource(StrEnum):
    TRAINING = "TRAINING"
    PHYSICAL_EXERTION = "PHYSICAL_EXERTION"
    MENTAL_STUDY = "MENTAL_STUDY"
    PERCEPTIVE_EXPERIENCE = "PERCEPTIVE_EXPERIENCE"
    RECOVERY_CHALLENGE = "RECOVERY_CHALLENGE"
    REAL_CHALLENGE = "REAL_CHALLENGE"


class CharacterResourceKey(StrEnum):
    HP = "HP"
    MANA = "MANA"
    STAMINA = "STAMINA"


class CombatEncounterStatus(StrEnum):
    ACTIVE = "ACTIVE"
    VICTORY = "VICTORY"
    DEFEAT = "DEFEAT"
    FLED = "FLED"
    CANCELLED = "CANCELLED"


class CombatActorType(StrEnum):
    CHARACTER = "CHARACTER"
    NPC = "NPC"
    SIMULATED_PLAYER = "SIMULATED_PLAYER"


class CombatRangeBand(StrEnum):
    ENGAGED = "ENGAGED"
    NEAR = "NEAR"
    FAR = "FAR"
    OUT_OF_REACH = "OUT_OF_REACH"


class CombatAwareness(StrEnum):
    AWARE = "AWARE"
    SURPRISED = "SURPRISED"
    UNAWARE = "UNAWARE"


class ResourceGrowthSource(StrEnum):
    ATTRIBUTE_DEVELOPMENT = "ATTRIBUTE_DEVELOPMENT"
    PHYSICAL_CONDITIONING = "PHYSICAL_CONDITIONING"
    RESOURCE_EXERTION = "RESOURCE_EXERTION"
    MAGICAL_PRACTICE = "MAGICAL_PRACTICE"
    TECHNIQUE_MASTERY = "TECHNIQUE_MASTERY"
    RECOVERY_CHALLENGE = "RECOVERY_CHALLENGE"
    REAL_CHALLENGE = "REAL_CHALLENGE"
    CLASS_PATH = "CLASS_PATH"


class DiscoveryStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    RUMORED = "RUMORED"
    DISCOVERED = "DISCOVERED"
    VISITED = "VISITED"
    MAPPED = "MAPPED"


class ConnectionType(StrEnum):
    ROAD = "ROAD"
    PATH = "PATH"
    RIVER = "RIVER"
    TRAIL = "TRAIL"


class ActionIntentType(StrEnum):
    MOVE = "MOVE"
    TALK = "TALK"
    EXAMINE = "EXAMINE"
    REST = "REST"
    WAIT = "WAIT"
    SKILL_CHECK = "SKILL_CHECK"
    TECHNIQUE = "TECHNIQUE"
    FREEFORM = "FREEFORM"
    UNKNOWN = "UNKNOWN"


class QuestStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class KnowerType(StrEnum):
    PLAYER = "PLAYER"
    NPC = "NPC"
    SIMULATED_PLAYER = "SIMULATED_PLAYER"


class MemoryOwnerType(StrEnum):
    WORLD = "WORLD"
    PLAYER = "PLAYER"
    NPC = "NPC"
    SIMULATED_PLAYER = "SIMULATED_PLAYER"


class KnowledgeCertainty(StrEnum):
    RUMOR = "RUMOR"
    BELIEVED = "BELIEVED"
    CONFIRMED = "CONFIRMED"


class SimulatedPlayerArchetype(StrEnum):
    EXPLORER = "EXPLORER"
    TRAINER = "TRAINER"
    SOCIAL = "SOCIAL"
    ADVENTURER = "ADVENTURER"

class SimulatedPlayerGoalType(StrEnum):
    NONE = "NONE"
    EXPLORE_REGION = "EXPLORE_REGION"
    TRAIN_SELF = "TRAIN_SELF"
    GATHER_KNOWLEDGE = "GATHER_KNOWLEDGE"
    SEEK_DANGER = "SEEK_DANGER"

class SimulatedPlayerActivity(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESTING = "RESTING"
    TRAINING = "TRAINING"
    SOCIALIZING = "SOCIALIZING"
    WORKING = "WORKING"

class SimulatedPlayerStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DEAD = "DEAD"

class RiskTolerance(StrEnum):
    CAUTIOUS = "CAUTIOUS"
    BALANCED = "BALANCED"
    BOLD = "BOLD"

class SimulatedPlayerGroupStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISSOLVED = "DISSOLVED"


class EventType(StrEnum):
    CAMPAIGN_CREATED = "CAMPAIGN_CREATED"
    WORLD_STARTED = "WORLD_STARTED"
    STORY_EXCHANGE = "STORY_EXCHANGE"
    CHARACTER_CREATED = "CHARACTER_CREATED"
    PLAYER_MOVED = "PLAYER_MOVED"
    TRAVEL_INCIDENT = "TRAVEL_INCIDENT"
    PLAYER_MET_NPC = "PLAYER_MET_NPC"
    PLAYER_TALKED_TO_NPC = "PLAYER_TALKED_TO_NPC"
    PLAYER_MET_SIMULATED_PLAYER = "PLAYER_MET_SIMULATED_PLAYER"
    PLAYER_TALKED_TO_SIMULATED_PLAYER = "PLAYER_TALKED_TO_SIMULATED_PLAYER"
    PLAYER_GAINED_ITEM = "PLAYER_GAINED_ITEM"
    PLAYER_LOST_ITEM = "PLAYER_LOST_ITEM"
    PLAYER_RESTED = "PLAYER_RESTED"
    PLAYER_GAINED_XP = "PLAYER_GAINED_XP"
    PLAYER_LEVELED_UP = "PLAYER_LEVELED_UP"
    PLAYER_GAINED_PROFESSION_XP = "PLAYER_GAINED_PROFESSION_XP"
    PLAYER_PROFESSION_LEVELED_UP = "PLAYER_PROFESSION_LEVELED_UP"
    PLAYER_COMPLETED_PROFESSION_ACTIVITY = "PLAYER_COMPLETED_PROFESSION_ACTIVITY"
    PLAYER_CLASS_OFFERED = "PLAYER_CLASS_OFFERED"
    PLAYER_CLASS_OFFER_DELAYED = "PLAYER_CLASS_OFFER_DELAYED"
    PLAYER_CLASS_ACCEPTED = "PLAYER_CLASS_ACCEPTED"
    PLAYER_ATTRIBUTE_INCREASED = "PLAYER_ATTRIBUTE_INCREASED"
    PLAYER_RESOURCE_MAX_INCREASED = "PLAYER_RESOURCE_MAX_INCREASED"
    PLAYER_DIED = "PLAYER_DIED"
    ACTION_CHECK_RESULT = "ACTION_CHECK_RESULT"
    COMBAT_STARTED = "COMBAT_STARTED"
    COMBAT_PARTICIPANT_JOINED = "COMBAT_PARTICIPANT_JOINED"
    COMBAT_PARTICIPANT_LEFT = "COMBAT_PARTICIPANT_LEFT"
    COMBAT_ENDED = "COMBAT_ENDED"
    QUEST_STARTED = "QUEST_STARTED"
    QUEST_OBJECTIVE_COMPLETED = "QUEST_OBJECTIVE_COMPLETED"
    QUEST_COMPLETED = "QUEST_COMPLETED"
    NPC_DIED = "NPC_DIED"
    REGION_DISCOVERED = "REGION_DISCOVERED"
    LOCATION_DISCOVERED = "LOCATION_DISCOVERED"
    LOCATION_VISITED = "LOCATION_VISITED"
    CONNECTION_DISCOVERED = "CONNECTION_DISCOVERED"
    BOSS_DISCOVERED = "BOSS_DISCOVERED"
    BOSS_DEFEATED = "BOSS_DEFEATED"
    NEW_TECHNIQUE_CREATED = "NEW_TECHNIQUE_CREATED"
    WORLD_TIME_ADVANCED = "WORLD_TIME_ADVANCED"
    WORLD_DEVELOPMENT_CREATED = "WORLD_DEVELOPMENT_CREATED"
    WORLD_DEVELOPMENT_UPDATED = "WORLD_DEVELOPMENT_UPDATED"
    WORLD_DEVELOPMENT_COMPLETED = "WORLD_DEVELOPMENT_COMPLETED"
    SIMULATED_PLAYER_TRAVEL_STARTED = "SIMULATED_PLAYER_TRAVEL_STARTED"
    SIMULATED_PLAYER_MOVED = "SIMULATED_PLAYER_MOVED"
    SIMULATED_PLAYER_TRAINED = "SIMULATED_PLAYER_TRAINED"
    SIMULATED_PLAYER_GAINED_XP = "SIMULATED_PLAYER_GAINED_XP"
    SIMULATED_PLAYER_LEVELED_UP = "SIMULATED_PLAYER_LEVELED_UP"
    SIMULATED_PLAYER_GOAL_COMPLETED = "SIMULATED_PLAYER_GOAL_COMPLETED"
    SIMULATED_PLAYER_GOAL_ASSIGNED = "SIMULATED_PLAYER_GOAL_ASSIGNED"
    SIMULATED_PLAYER_DIED = "SIMULATED_PLAYER_DIED"
    SIMULATED_PLAYER_GROUP_CREATED = "SIMULATED_PLAYER_GROUP_CREATED"
    SIMULATED_PLAYER_GROUP_JOINED = "SIMULATED_PLAYER_GROUP_JOINED"
    SIMULATED_PLAYER_GROUP_LEFT = "SIMULATED_PLAYER_GROUP_LEFT"
    SIMULATED_PLAYER_GROUP_DISSOLVED = "SIMULATED_PLAYER_GROUP_DISSOLVED"
    SIMULATED_PLAYER_GROUP_TRAVEL_STARTED = "SIMULATED_PLAYER_GROUP_TRAVEL_STARTED"
    SIMULATED_PLAYER_WORLD_ARRIVAL = "SIMULATED_PLAYER_WORLD_ARRIVAL"
    RELATIONSHIP_CHANGED = "RELATIONSHIP_CHANGED"
    KNOWLEDGE_PROPAGATED = "KNOWLEDGE_PROPAGATED"
    SOCIAL_KNOWLEDGE_OPPORTUNITY_RESOLVED = (
        "SOCIAL_KNOWLEDGE_OPPORTUNITY_RESOLVED"
    )

class TravelPace(StrEnum):
    SLOW = "SLOW"
    NORMAL = "NORMAL"
    FAST = "FAST"

class NPCActivity(StrEnum):
    RESTING = "RESTING"
    WORKING = "WORKING"
    AVAILABLE = "AVAILABLE"
    
class WorldDevelopmentType(StrEnum):
    CONSTRUCTION = "CONSTRUCTION"

class WorldDevelopmentStatus(StrEnum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class TravelIncidentKind(StrEnum):
    DELAY = "DELAY"
    FATIGUE = "FATIGUE"
