from enum import StrEnum


class CharacterStatus(StrEnum):
    ALIVE = "ALIVE"
    DEAD = "DEAD"


class DiscoveryStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    RUMORED = "RUMORED"
    DISCOVERED = "DISCOVERED"
    VISITED = "VISITED"
    MAPPED = "MAPPED"


class ConnectionType(StrEnum):
    ROAD = "ROAD"
    PATH = "PATH"
    RIVER = "RIVER"
    TRAIL = "TRAIL"


class ActionIntentType(StrEnum):
    MOVE = "MOVE"
    TALK = "TALK"
    EXAMINE = "EXAMINE"
    REST = "REST"
    WAIT = "WAIT"
    SKILL_CHECK = "SKILL_CHECK"
    FREEFORM = "FREEFORM"
    UNKNOWN = "UNKNOWN"


class QuestStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class KnowerType(StrEnum):
    PLAYER = "PLAYER"
    NPC = "NPC"
    SIMULATED_PLAYER = "SIMULATED_PLAYER"


class MemoryOwnerType(StrEnum):
    WORLD = "WORLD"
    PLAYER = "PLAYER"
    NPC = "NPC"
    SIMULATED_PLAYER = "SIMULATED_PLAYER"


class KnowledgeCertainty(StrEnum):
    RUMOR = "RUMOR"
    BELIEVED = "BELIEVED"
    CONFIRMED = "CONFIRMED"


class SimulatedPlayerArchetype(StrEnum):
    EXPLORER = "EXPLORER"
    TRAINER = "TRAINER"
    SOCIAL = "SOCIAL"
    ADVENTURER = "ADVENTURER"


class SimulatedPlayerStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DEAD = "DEAD"


class EventType(StrEnum):
    CAMPAIGN_CREATED = "CAMPAIGN_CREATED"
    WORLD_STARTED = "WORLD_STARTED"
    STORY_EXCHANGE = "STORY_EXCHANGE"
    CHARACTER_CREATED = "CHARACTER_CREATED"
    PLAYER_MOVED = "PLAYER_MOVED"
    TRAVEL_INCIDENT = "TRAVEL_INCIDENT"
    PLAYER_MET_NPC = "PLAYER_MET_NPC"
    PLAYER_TALKED_TO_NPC = "PLAYER_TALKED_TO_NPC"
    PLAYER_GAINED_ITEM = "PLAYER_GAINED_ITEM"
    PLAYER_LOST_ITEM = "PLAYER_LOST_ITEM"
    PLAYER_RESTED = "PLAYER_RESTED"
    PLAYER_GAINED_XP = "PLAYER_GAINED_XP"
    PLAYER_LEVELED_UP = "PLAYER_LEVELED_UP"
    PLAYER_DIED = "PLAYER_DIED"
    ACTION_CHECK_RESULT = "ACTION_CHECK_RESULT"
    QUEST_STARTED = "QUEST_STARTED"
    QUEST_OBJECTIVE_COMPLETED = "QUEST_OBJECTIVE_COMPLETED"
    QUEST_COMPLETED = "QUEST_COMPLETED"
    NPC_DIED = "NPC_DIED"
    REGION_DISCOVERED = "REGION_DISCOVERED"
    LOCATION_DISCOVERED = "LOCATION_DISCOVERED"
    LOCATION_VISITED = "LOCATION_VISITED"
    CONNECTION_DISCOVERED = "CONNECTION_DISCOVERED"
    BOSS_DISCOVERED = "BOSS_DISCOVERED"
    BOSS_DEFEATED = "BOSS_DEFEATED"
    NEW_TECHNIQUE_CREATED = "NEW_TECHNIQUE_CREATED"
    WORLD_TIME_ADVANCED = "WORLD_TIME_ADVANCED"
    SIMULATED_PLAYER_MOVED = "SIMULATED_PLAYER_MOVED"
    SIMULATED_PLAYER_TRAINED = "SIMULATED_PLAYER_TRAINED"
    RELATIONSHIP_CHANGED = "RELATIONSHIP_CHANGED"
    KNOWLEDGE_PROPAGATED = "KNOWLEDGE_PROPAGATED"

class TravelPace(StrEnum):
    SLOW = "SLOW"
    NORMAL = "NORMAL"
    FAST = "FAST"

class NPCActivity(StrEnum):
    RESTING = "RESTING"
    WORKING = "WORKING"
    AVAILABLE = "AVAILABLE"

class TravelIncidentKind(StrEnum):
    DELAY = "DELAY"
    FATIGUE = "FATIGUE"