from enum import StrEnum


class CharacterStatus(StrEnum):
    ALIVE = "ALIVE"
    INCAPACITATED = "INCAPACITATED"
    DEAD = "DEAD"


class CharacterXPSource(StrEnum):
    DANGER_OVERCOME = "DANGER_OVERCOME"
    SIGNIFICANT_CHALLENGE = "SIGNIFICANT_CHALLENGE"
    IMPORTANT_DISCOVERY = "IMPORTANT_DISCOVERY"
    RELEVANT_ACHIEVEMENT = "RELEVANT_ACHIEVEMENT"
    DIFFICULT_SURVIVAL = "DIFFICULT_SURVIVAL"
    IMPORTANT_OBJECTIVE = "IMPORTANT_OBJECTIVE"
    DIFFICULT_PROBLEM = "DIFFICULT_PROBLEM"
    MEANINGFUL_NEW_EXPERIENCE = "MEANINGFUL_NEW_EXPERIENCE"


class EarthProfession(StrEnum):
    CHEF = "CHEF"
    FARMER = "FARMER"
    CARPENTER = "CARPENTER"
    BLACKSMITH = "BLACKSMITH"


class ProfessionXPSource(StrEnum):
    GATHERING = "GATHERING"
    WORK = "WORK"
    CRAFTING = "CRAFTING"
    PRACTICE = "PRACTICE"


class ProfessionActivityOutcome(StrEnum):
    FAILURE = "FAILURE"
    PARTIAL = "PARTIAL"
    SUCCESS = "SUCCESS"


class ClassOfferStatus(StrEnum):
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    DELAYED = "DELAYED"
    ACCEPTED = "ACCEPTED"


class DomainEvidenceSource(StrEnum):
    TRAINING = "TRAINING"
    TECHNIQUE_LEARNED = "TECHNIQUE_LEARNED"
    TECHNIQUE_USED = "TECHNIQUE_USED"
    EXPERIENCE = "EXPERIENCE"
    COMBAT = "COMBAT"
    STUDY = "STUDY"
    EXPERIMENTATION = "EXPERIMENTATION"
    ACHIEVEMENT = "ACHIEVEMENT"


class TechniqueType(StrEnum):
    """What powers a technique's execution — not which world system consumes
    it (combat/crafting/exploration/...); that routing is a later concern."""

    PHYSICAL = "PHYSICAL"
    MAGICAL = "MAGICAL"
    HYBRID = "HYBRID"


class TechniqueLearningState(StrEnum):
    """A character's progress toward actually being able to perform a
    technique. Absence of a CharacterTechnique row means UNKNOWN — there is
    no explicit UNKNOWN member, matching how the rest of the project treats
    missing knowledge as ignorance rather than a stored state."""

    AWARE = "AWARE"
    LEARNING = "LEARNING"
    LEARNED = "LEARNED"


class TechniqueOrigin(StrEnum):
    """How a character came to know about / learn a technique."""

    SELF_DISCOVERED = "SELF_DISCOVERED"
    TAUGHT = "TAUGHT"
    OBSERVED = "OBSERVED"
    DOCUMENTED = "DOCUMENTED"


class TechniqueMasteryTier(StrEnum):
    """How reliably a LEARNED technique can be executed — not a level, and
    never a stand-in for damage. See app.game.skills.technique_mastery."""

    UNSTABLE = "UNSTABLE"
    BASIC = "BASIC"
    PRACTICED = "PRACTICED"
    REFINED = "REFINED"
    MASTERED = "MASTERED"


class CharacterAttributeKey(StrEnum):
    STRENGTH = "STRENGTH"
    AGILITY = "AGILITY"
    VITALITY = "VITALITY"
    INTELLIGENCE = "INTELLIGENCE"
    WISDOM = "WISDOM"
    ENDURANCE = "ENDURANCE"
    LUCK = "LUCK"


class AttributeEvidenceSource(StrEnum):
    TRAINING = "TRAINING"
    PHYSICAL_EXERTION = "PHYSICAL_EXERTION"
    MENTAL_STUDY = "MENTAL_STUDY"
    PERCEPTIVE_EXPERIENCE = "PERCEPTIVE_EXPERIENCE"
    RECOVERY_CHALLENGE = "RECOVERY_CHALLENGE"
    REAL_CHALLENGE = "REAL_CHALLENGE"


class CharacterResourceKey(StrEnum):
    HP = "HP"
    MANA = "MANA"
    STAMINA = "STAMINA"


class ItemType(StrEnum):
    MISC = "MISC"
    MATERIAL = "MATERIAL"
    CURRENCY = "CURRENCY"
    AMMUNITION = "AMMUNITION"
    CONSUMABLE = "CONSUMABLE"
    WEAPON = "WEAPON"
    ARMOR = "ARMOR"
    TOOL = "TOOL"
    CONTAINER = "CONTAINER"
    QUEST = "QUEST"


class ItemInstanceMode(StrEnum):
    STACKABLE = "STACKABLE"
    UNIQUE = "UNIQUE"


class ItemQuality(StrEnum):
    CRUDE = "CRUDE"
    POOR = "POOR"
    STANDARD = "STANDARD"
    GOOD = "GOOD"
    EXCELLENT = "EXCELLENT"
    MASTERWORK = "MASTERWORK"


class ItemCondition(StrEnum):
    EXCELLENT = "EXCELLENT"
    GOOD = "GOOD"
    WORN = "WORN"
    DAMAGED = "DAMAGED"
    CRITICAL = "CRITICAL"
    BROKEN = "BROKEN"


class ItemWearSeverity(StrEnum):
    NEGLIGIBLE = "NEGLIGIBLE"
    LIGHT = "LIGHT"
    MODERATE = "MODERATE"
    SEVERE = "SEVERE"
    DEVASTATING = "DEVASTATING"


class ItemLocationType(StrEnum):
    UNPLACED = "UNPLACED"
    CHARACTER = "CHARACTER"
    CHARACTER_EQUIPPED = "CHARACTER_EQUIPPED"
    NPC = "NPC"
    WORLD_LOCATION = "WORLD_LOCATION"
    CONTAINER = "CONTAINER"


class ItemOwnerType(StrEnum):
    NONE = "NONE"
    CHARACTER = "CHARACTER"
    NPC = "NPC"


class EncumbranceTier(StrEnum):
    NORMAL = "NORMAL"
    LIGHTLY_ENCUMBERED = "LIGHTLY_ENCUMBERED"
    HEAVILY_ENCUMBERED = "HEAVILY_ENCUMBERED"
    OVERLOADED = "OVERLOADED"


class ItemAccessibility(StrEnum):
    IMMEDIATE = "IMMEDIATE"
    QUICK = "QUICK"
    WORN = "WORN"
    STOWED = "STOWED"


class WeaponFamily(StrEnum):
    DAGGER = "DAGGER"
    KNIFE = "KNIFE"
    SWORD = "SWORD"
    AXE = "AXE"
    HAMMER = "HAMMER"
    MACE = "MACE"
    SPEAR = "SPEAR"
    POLEARM = "POLEARM"
    BOW = "BOW"
    CROSSBOW = "CROSSBOW"
    SLING = "SLING"
    STAFF = "STAFF"
    CLUB = "CLUB"


class PhysicalDamageProfile(StrEnum):
    SLASH = "SLASH"
    PIERCE = "PIERCE"
    BLUNT = "BLUNT"


class BodyArea(StrEnum):
    HEAD = "HEAD"
    TORSO = "TORSO"
    ARMS = "ARMS"
    HANDS = "HANDS"
    LEGS = "LEGS"
    FEET = "FEET"


class ToolCapability(StrEnum):
    HAMMERING = "HAMMERING"
    CUTTING = "CUTTING"
    MINING = "MINING"
    SAWING = "SAWING"
    COOKING = "COOKING"
    FISHING = "FISHING"
    SEWING = "SEWING"
    LOCKPICKING = "LOCKPICKING"


class WeaponReach(StrEnum):
    NORMAL = "NORMAL"
    LONG = "LONG"
    RANGED = "RANGED"


class WeaponHandRequirement(StrEnum):
    ONE_HAND = "ONE_HAND"
    ONE_OR_TWO_HANDS = "ONE_OR_TWO_HANDS"
    TWO_HANDS = "TWO_HANDS"


class CombatEncounterStatus(StrEnum):
    ACTIVE = "ACTIVE"
    VICTORY = "VICTORY"
    DEFEAT = "DEFEAT"
    FLED = "FLED"
    CANCELLED = "CANCELLED"


class CombatActorType(StrEnum):
    CHARACTER = "CHARACTER"
    NPC = "NPC"
    SIMULATED_PLAYER = "SIMULATED_PLAYER"


class CombatRangeBand(StrEnum):
    ENGAGED = "ENGAGED"
    NEAR = "NEAR"
    FAR = "FAR"
    OUT_OF_REACH = "OUT_OF_REACH"


class CombatAwareness(StrEnum):
    AWARE = "AWARE"
    SURPRISED = "SURPRISED"
    UNAWARE = "UNAWARE"


class CombatTurnStatus(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"


class CombatActionType(StrEnum):
    MELEE_ATTACK = "MELEE_ATTACK"
    RANGED_ATTACK = "RANGED_ATTACK"


class CombatActionOutcome(StrEnum):
    CRITICAL_MISS = "CRITICAL_MISS"
    MISS = "MISS"
    HIT = "HIT"
    CRITICAL_HIT = "CRITICAL_HIT"


class CombatDamageType(StrEnum):
    PHYSICAL = "PHYSICAL"
    FIRE = "FIRE"
    COLD = "COLD"
    LIGHTNING = "LIGHTNING"
    POISON = "POISON"
    ARCANE = "ARCANE"


class CombatIncapacitationStatus(StrEnum):
    CRITICAL = "CRITICAL"
    STABILIZED = "STABILIZED"
    RECOVERED = "RECOVERED"
    DEAD = "DEAD"


class EquipmentSlot(StrEnum):
    HEAD = "HEAD"
    TORSO = "TORSO"
    BODY = "TORSO"  # compatibility alias for Phase 9 callers
    LEGS = "LEGS"
    HANDS = "HANDS"
    FEET = "FEET"
    MAIN_HAND = "MAIN_HAND"
    OFF_HAND = "OFF_HAND"
    BOTH_HANDS = "BOTH_HANDS"
    BACK = "BACK"
    WAIST = "WAIST"
    ACCESSORY = "ACCESSORY"


class CombatConditionType(StrEnum):
    STUNNED = "STUNNED"
    WEAKENED = "WEAKENED"
    EXPOSED = "EXPOSED"
    GUARDED = "GUARDED"
    DODGING = "DODGING"


class CombatTacticalActionType(StrEnum):
    GUARD = "GUARD"
    DODGE = "DODGE"
    APPROACH = "APPROACH"
    RETREAT = "RETREAT"
    DISENGAGE = "DISENGAGE"
    FLEE = "FLEE"
    WAIT = "WAIT"


class CombatDecisionKind(StrEnum):
    ATTACK = "ATTACK"
    TACTICAL = "TACTICAL"


class RecoveryType(StrEnum):
    SHORT_REST = "SHORT_REST"


class ResourceGrowthSource(StrEnum):
    ATTRIBUTE_DEVELOPMENT = "ATTRIBUTE_DEVELOPMENT"
    PHYSICAL_CONDITIONING = "PHYSICAL_CONDITIONING"
    RESOURCE_EXERTION = "RESOURCE_EXERTION"
    MAGICAL_PRACTICE = "MAGICAL_PRACTICE"
    TECHNIQUE_MASTERY = "TECHNIQUE_MASTERY"
    RECOVERY_CHALLENGE = "RECOVERY_CHALLENGE"
    REAL_CHALLENGE = "REAL_CHALLENGE"
    CLASS_PATH = "CLASS_PATH"


class DiscoveryStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    RUMORED = "RUMORED"
    DISCOVERED = "DISCOVERED"
    VISITED = "VISITED"
    MAPPED = "MAPPED"


class ConnectionType(StrEnum):
    ROAD = "ROAD"
    PATH = "PATH"
    RIVER = "RIVER"
    TRAIL = "TRAIL"


class ActionIntentType(StrEnum):
    MOVE = "MOVE"
    TALK = "TALK"
    EXAMINE = "EXAMINE"
    REST = "REST"
    WAIT = "WAIT"
    SKILL_CHECK = "SKILL_CHECK"
    TECHNIQUE = "TECHNIQUE"
    EXPERIMENT = "EXPERIMENT"
    ATTACK = "ATTACK"
    DEFEND = "DEFEND"
    DODGE = "DODGE"
    APPROACH = "APPROACH"
    RETREAT = "RETREAT"
    DISENGAGE = "DISENGAGE"
    FLEE = "FLEE"
    PICK_UP = "PICK_UP"
    DROP = "DROP"
    GIVE = "GIVE"
    TAKE = "TAKE"
    EQUIP = "EQUIP"
    UNEQUIP = "UNEQUIP"
    STORE = "STORE"
    RETRIEVE = "RETRIEVE"
    MOVE_BETWEEN_CONTAINERS = "MOVE_BETWEEN_CONTAINERS"
    FREEFORM = "FREEFORM"
    UNKNOWN = "UNKNOWN"


class QuestStatus(StrEnum):
    """Shared across two distinct levels — see app.game.quests.service.

    World-level (Quest.status): whether the situation is still an open,
    unclaimed opportunity. AVAILABLE is the only non-terminal value; EXPIRED/
    CANCELLED/RESOLVED_EXTERNALLY mean the world moved on, independent of
    any one character.

    Character-level (CharacterQuest.status): one character's participation.
    NOT_STARTED is reserved for Phase 12J (quest awareness via the Knowledge
    system, distinct from participation) and unused until then.
    """

    AVAILABLE = "AVAILABLE"
    NOT_STARTED = "NOT_STARTED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    RESOLVED_EXTERNALLY = "RESOLVED_EXTERNALLY"


class ObjectiveType(StrEnum):
    """The kind of involvement an Objective represents — a display/
    organization category, not a mechanical trigger (see
    ObjectiveTriggerType for that)."""

    INVESTIGATION = "INVESTIGATION"
    DISCOVERY = "DISCOVERY"
    DELIVERY = "DELIVERY"
    PROTECTION = "PROTECTION"
    NEGOTIATION = "NEGOTIATION"
    EXPLORATION = "EXPLORATION"
    RETRIEVAL = "RETRIEVAL"
    SURVIVAL = "SURVIVAL"
    OBSERVATION = "OBSERVATION"
    COMBAT = "COMBAT"
    CRAFTING = "CRAFTING"
    SOCIAL_INTERACTION = "SOCIAL_INTERACTION"
    WORLD_STATE_CHANGE = "WORLD_STATE_CHANGE"


class ObjectiveTriggerType(StrEnum):
    """What authoritative backend fact the Objective Evaluator
    (app.game.quests.service.evaluate_objective_trigger) watches for.
    MANUAL means no automatic evaluator exists yet for this objective —
    only an explicit complete_objective call can satisfy it. Not every
    ObjectiveType has a generic trigger wired yet; see the Phase 12B
    report for which of these have a live call site today."""

    TALK_TO_NPC = "TALK_TO_NPC"
    REACH_LOCATION = "REACH_LOCATION"
    DELIVER_ITEM = "DELIVER_ITEM"
    RETRIEVE_ITEM = "RETRIEVE_ITEM"
    DEFEAT_TARGET = "DEFEAT_TARGET"
    MANUAL = "MANUAL"


class NoticeCategory(StrEnum):
    """What kind of posting this is — not every category implies a Quest
    (Phase 12I). QUEST_REQUEST is the only one that typically carries a
    quest_id link; the rest are informational or point at other systems
    that don't exist yet (jobs/trade → Phase 14)."""

    QUEST_REQUEST = "QUEST_REQUEST"
    JOB = "JOB"
    TRADE = "TRADE"
    WANTED = "WANTED"
    ANNOUNCEMENT = "ANNOUNCEMENT"
    WARNING = "WARNING"
    RECRUITMENT = "RECRUITMENT"
    TRAVEL = "TRAVEL"
    LOST_PROPERTY = "LOST_PROPERTY"
    MISSING_PERSON = "MISSING_PERSON"
    SERVICE_OFFER = "SERVICE_OFFER"
    RUMOR = "RUMOR"
    COMMUNITY_NOTICE = "COMMUNITY_NOTICE"


class NoticeStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CLAIMED = "CLAIMED"
    COMPLETED = "COMPLETED"
    EXPIRED = "EXPIRED"
    WITHDRAWN = "WITHDRAWN"
    OUTDATED = "OUTDATED"
    REMOVED = "REMOVED"


class QuestSource(StrEnum):
    """Where a Quest originated. Phase 12A only defines the vocabulary —
    ORGANIZATION_REQUEST/NOTICE_BOARD/WORLD_EVENT sources are not yet wired
    to any producer (that's Phase 12H/12I/13); SELF_DISCOVERED is the
    default for quests without a more specific origin."""

    NPC_REQUEST = "NPC_REQUEST"
    ORGANIZATION_REQUEST = "ORGANIZATION_REQUEST"
    NOTICE_BOARD = "NOTICE_BOARD"
    WORLD_EVENT = "WORLD_EVENT"
    SELF_DISCOVERED = "SELF_DISCOVERED"
    OFFICIAL_CONTRACT = "OFFICIAL_CONTRACT"
    EMERGENT_SITUATION = "EMERGENT_SITUATION"


class KnowerType(StrEnum):
    PLAYER = "PLAYER"
    NPC = "NPC"
    SIMULATED_PLAYER = "SIMULATED_PLAYER"


class MemoryOwnerType(StrEnum):
    WORLD = "WORLD"
    PLAYER = "PLAYER"
    NPC = "NPC"
    SIMULATED_PLAYER = "SIMULATED_PLAYER"


class KnowledgeCertainty(StrEnum):
    RUMOR = "RUMOR"
    BELIEVED = "BELIEVED"
    CONFIRMED = "CONFIRMED"


class SimulatedPlayerArchetype(StrEnum):
    EXPLORER = "EXPLORER"
    TRAINER = "TRAINER"
    SOCIAL = "SOCIAL"
    ADVENTURER = "ADVENTURER"

class SimulatedPlayerGoalType(StrEnum):
    NONE = "NONE"
    EXPLORE_REGION = "EXPLORE_REGION"
    TRAIN_SELF = "TRAIN_SELF"
    GATHER_KNOWLEDGE = "GATHER_KNOWLEDGE"
    SEEK_DANGER = "SEEK_DANGER"

class SimulatedPlayerActivity(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESTING = "RESTING"
    TRAINING = "TRAINING"
    SOCIALIZING = "SOCIALIZING"
    WORKING = "WORKING"

class SimulatedPlayerStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INCAPACITATED = "INCAPACITATED"
    DEAD = "DEAD"

class RiskTolerance(StrEnum):
    CAUTIOUS = "CAUTIOUS"
    BALANCED = "BALANCED"
    BOLD = "BOLD"

class SimulatedPlayerGroupStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISSOLVED = "DISSOLVED"


class EventType(StrEnum):
    CAMPAIGN_CREATED = "CAMPAIGN_CREATED"
    WORLD_STARTED = "WORLD_STARTED"
    STORY_EXCHANGE = "STORY_EXCHANGE"
    CHARACTER_CREATED = "CHARACTER_CREATED"
    PLAYER_MOVED = "PLAYER_MOVED"
    TRAVEL_INCIDENT = "TRAVEL_INCIDENT"
    PLAYER_MET_NPC = "PLAYER_MET_NPC"
    PLAYER_TALKED_TO_NPC = "PLAYER_TALKED_TO_NPC"
    PLAYER_MET_SIMULATED_PLAYER = "PLAYER_MET_SIMULATED_PLAYER"
    PLAYER_TALKED_TO_SIMULATED_PLAYER = "PLAYER_TALKED_TO_SIMULATED_PLAYER"
    PLAYER_GAINED_ITEM = "PLAYER_GAINED_ITEM"
    PLAYER_LOST_ITEM = "PLAYER_LOST_ITEM"
    ITEM_LOCATION_CHANGED = "ITEM_LOCATION_CHANGED"
    ITEM_OWNERSHIP_CHANGED = "ITEM_OWNERSHIP_CHANGED"
    ITEM_EQUIPPED = "ITEM_EQUIPPED"
    ITEM_UNEQUIPPED = "ITEM_UNEQUIPPED"
    ITEM_WEAR_APPLIED = "ITEM_WEAR_APPLIED"
    ITEM_BROKEN = "ITEM_BROKEN"
    ITEM_INTERACTION_RESOLVED = "ITEM_INTERACTION_RESOLVED"
    PLAYER_RESTED = "PLAYER_RESTED"
    PLAYER_GAINED_XP = "PLAYER_GAINED_XP"
    PLAYER_LEVELED_UP = "PLAYER_LEVELED_UP"
    PLAYER_GAINED_PROFESSION_XP = "PLAYER_GAINED_PROFESSION_XP"
    PLAYER_PROFESSION_LEVELED_UP = "PLAYER_PROFESSION_LEVELED_UP"
    PLAYER_COMPLETED_PROFESSION_ACTIVITY = "PLAYER_COMPLETED_PROFESSION_ACTIVITY"
    PLAYER_CLASS_OFFERED = "PLAYER_CLASS_OFFERED"
    PLAYER_CLASS_OFFER_DELAYED = "PLAYER_CLASS_OFFER_DELAYED"
    PLAYER_CLASS_ACCEPTED = "PLAYER_CLASS_ACCEPTED"
    PLAYER_ATTRIBUTE_INCREASED = "PLAYER_ATTRIBUTE_INCREASED"
    PLAYER_RESOURCE_MAX_INCREASED = "PLAYER_RESOURCE_MAX_INCREASED"
    PLAYER_DIED = "PLAYER_DIED"
    ACTION_CHECK_RESULT = "ACTION_CHECK_RESULT"
    COMBAT_STARTED = "COMBAT_STARTED"
    COMBAT_PARTICIPANT_JOINED = "COMBAT_PARTICIPANT_JOINED"
    COMBAT_PARTICIPANT_LEFT = "COMBAT_PARTICIPANT_LEFT"
    COMBAT_INITIATIVE_ROLLED = "COMBAT_INITIATIVE_ROLLED"
    COMBAT_TURN_ADVANCED = "COMBAT_TURN_ADVANCED"
    COMBAT_ACTION_RESOLVED = "COMBAT_ACTION_RESOLVED"
    COMBAT_DAMAGE_APPLIED = "COMBAT_DAMAGE_APPLIED"
    COMBAT_PARTICIPANT_INCAPACITATED = "COMBAT_PARTICIPANT_INCAPACITATED"
    COMBAT_CRITICAL_CHECK_RESOLVED = "COMBAT_CRITICAL_CHECK_RESOLVED"
    COMBAT_PARTICIPANT_STABILIZED = "COMBAT_PARTICIPANT_STABILIZED"
    COMBAT_PARTICIPANT_RECOVERED = "COMBAT_PARTICIPANT_RECOVERED"
    COMBAT_RESOURCE_SPENT = "COMBAT_RESOURCE_SPENT"
    COMBAT_CONDITION_APPLIED = "COMBAT_CONDITION_APPLIED"
    COMBAT_CONDITION_TRIGGERED = "COMBAT_CONDITION_TRIGGERED"
    COMBAT_CONDITION_EXPIRED = "COMBAT_CONDITION_EXPIRED"
    COMBAT_CONDITION_REMOVED = "COMBAT_CONDITION_REMOVED"
    COMBAT_TACTICAL_ACTION_RESOLVED = "COMBAT_TACTICAL_ACTION_RESOLVED"
    COMBAT_AUTONOMOUS_DECISION_RESOLVED = "COMBAT_AUTONOMOUS_DECISION_RESOLVED"
    COMBAT_ENDED = "COMBAT_ENDED"
    QUEST_STARTED = "QUEST_STARTED"
    QUEST_OBJECTIVE_COMPLETED = "QUEST_OBJECTIVE_COMPLETED"
    QUEST_COMPLETED = "QUEST_COMPLETED"
    QUEST_FAILED = "QUEST_FAILED"
    QUEST_CANCELLED = "QUEST_CANCELLED"
    QUEST_EXPIRED = "QUEST_EXPIRED"
    QUEST_RESOLVED_EXTERNALLY = "QUEST_RESOLVED_EXTERNALLY"
    NOTICE_POSTED = "NOTICE_POSTED"
    NOTICE_WITHDRAWN = "NOTICE_WITHDRAWN"
    NOTICE_EXPIRED = "NOTICE_EXPIRED"
    NOTICE_UPDATED = "NOTICE_UPDATED"
    NPC_DIED = "NPC_DIED"
    REGION_DISCOVERED = "REGION_DISCOVERED"
    LOCATION_DISCOVERED = "LOCATION_DISCOVERED"
    LOCATION_VISITED = "LOCATION_VISITED"
    CONNECTION_DISCOVERED = "CONNECTION_DISCOVERED"
    BOSS_DISCOVERED = "BOSS_DISCOVERED"
    BOSS_DEFEATED = "BOSS_DEFEATED"
    NEW_TECHNIQUE_CREATED = "NEW_TECHNIQUE_CREATED"
    TECHNIQUE_AWARENESS_GAINED = "TECHNIQUE_AWARENESS_GAINED"
    TECHNIQUE_LEARNING_STARTED = "TECHNIQUE_LEARNING_STARTED"
    TECHNIQUE_LEARNED = "TECHNIQUE_LEARNED"
    TECHNIQUE_RECOGNIZED = "TECHNIQUE_RECOGNIZED"
    WORLD_TIME_ADVANCED = "WORLD_TIME_ADVANCED"
    WORLD_DEVELOPMENT_CREATED = "WORLD_DEVELOPMENT_CREATED"
    WORLD_DEVELOPMENT_UPDATED = "WORLD_DEVELOPMENT_UPDATED"
    WORLD_DEVELOPMENT_COMPLETED = "WORLD_DEVELOPMENT_COMPLETED"
    SIMULATED_PLAYER_TRAVEL_STARTED = "SIMULATED_PLAYER_TRAVEL_STARTED"
    SIMULATED_PLAYER_MOVED = "SIMULATED_PLAYER_MOVED"
    SIMULATED_PLAYER_TRAINED = "SIMULATED_PLAYER_TRAINED"
    SIMULATED_PLAYER_GAINED_XP = "SIMULATED_PLAYER_GAINED_XP"
    SIMULATED_PLAYER_LEVELED_UP = "SIMULATED_PLAYER_LEVELED_UP"
    SIMULATED_PLAYER_GOAL_COMPLETED = "SIMULATED_PLAYER_GOAL_COMPLETED"
    SIMULATED_PLAYER_GOAL_ASSIGNED = "SIMULATED_PLAYER_GOAL_ASSIGNED"
    SIMULATED_PLAYER_DIED = "SIMULATED_PLAYER_DIED"
    SIMULATED_PLAYER_GROUP_CREATED = "SIMULATED_PLAYER_GROUP_CREATED"
    SIMULATED_PLAYER_GROUP_JOINED = "SIMULATED_PLAYER_GROUP_JOINED"
    SIMULATED_PLAYER_GROUP_LEFT = "SIMULATED_PLAYER_GROUP_LEFT"
    SIMULATED_PLAYER_GROUP_DISSOLVED = "SIMULATED_PLAYER_GROUP_DISSOLVED"
    SIMULATED_PLAYER_GROUP_TRAVEL_STARTED = "SIMULATED_PLAYER_GROUP_TRAVEL_STARTED"
    SIMULATED_PLAYER_WORLD_ARRIVAL = "SIMULATED_PLAYER_WORLD_ARRIVAL"
    RELATIONSHIP_CHANGED = "RELATIONSHIP_CHANGED"
    KNOWLEDGE_PROPAGATED = "KNOWLEDGE_PROPAGATED"
    SOCIAL_KNOWLEDGE_OPPORTUNITY_RESOLVED = (
        "SOCIAL_KNOWLEDGE_OPPORTUNITY_RESOLVED"
    )

class TravelPace(StrEnum):
    SLOW = "SLOW"
    NORMAL = "NORMAL"
    FAST = "FAST"

class NPCActivity(StrEnum):
    RESTING = "RESTING"
    WORKING = "WORKING"
    AVAILABLE = "AVAILABLE"
    
class WorldDevelopmentType(StrEnum):
    CONSTRUCTION = "CONSTRUCTION"

class WorldDevelopmentStatus(StrEnum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class TravelIncidentKind(StrEnum):
    DELAY = "DELAY"
    FATIGUE = "FATIGUE"
